version: "3"
services:

  # docker run -d
  # --hostname rabbit
  # --name rabbitmq
  # -p 9090:1567
  # -e RABBITMQ_DEFAULT_USER=$RASPBERRYPI_USER
  # -e RABBITMQ_DEFAULT_PASS=$RASPBERRYPI_PASSWORD
  # rabbitmq:3.7-management-alpine
  rabbitmq:
    image: "rabbitmq:3.7-management-alpine"
    hostname: rabbit
    ports:
      - 9090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RASPBERRYPI_USER}
      - RABBITMQ_DEFAULT_PASS=${RASPBERRYPI_PASSWORD}
    
  # docker run -d
  # --name ping-pong
  # --link rabbitmq
  # --volume $(realpath ./ping-pong):/ping-pong
  # -e USER=$RASPBERRYPI_USER
  # -e PASSWORD=$RASPBERRYPI_PASSWORD
  # -w /ping-pong
  # node:9.4-slim
  # bash -c "npm install && node player.js"
  ping-pong:
    image: "node:9.4-slim"
    links:
      - rabbitmq
    volumes:
      - ./ping-pong:/ping-pong
    environment:
      - USER=${RASPBERRYPI_USER}
      - PASSWORD=${RASPBERRYPI_PASSWORD}
    working_dir: /ping-pong
    command: node player.js

  # docker build -t web ./web
  # docker run -d
  # --name web
  # --link rabbitmq
  # -p 8080:8080
  # -e USER=$RASPBERRYPI_USER
  # -e PASSWORD=$RASPBERRYPI_PASSWORD
  # web
  web:
    build: ./web
    links:
      - rabbitmq
    environment:
      - USER=${RASPBERRYPI_USER}
      - PASSWORD=${RASPBERRYPI_PASSWORD}
    volumes:
      - ./web:/web
    ports:
      - 8080:8080
