version: "3"
services:

  # docker run -d --hostname rabbit --name rabbitmq -p 9090:15672 -e RABBITMQ_DEFAULT_USER=pi -e RABBITMQ_DEFAULT_PASS=qwer1234 rabbitmq:3.7-management-alpine
  rabbitmq:
    image: "rabbitmq:3.7-management-alpine"
    hostname: rabbit
    ports:
      - 9090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RASPBERRYPI_USER}
      - RABBITMQ_DEFAULT_PASS=${RASPBERRYPI_PASSWORD}
    
  # docker run -d --name ping-pong --link rabbitmq --volume $(realpath ./ping-pong):/ping-pong -e USER=pi -e PASSWORD=qwer1234 -w /ping-pong node:9.4-slim bash -c "npm install && node player.js"
  ping-pong:
    image: "node:9.4-slim"
    links:
      - rabbitmq
    volumes:
      - ./ping-pong:/ping-pong
    environment:
      - USER=${RASPBERRYPI_USER}
      - PASSWORD=${RASPBERRYPI_PASSWORD}
    working_dir: /ping-pong
    command: node player.js

  # docker run -d --name web -p 8080:8080 --volume $(realpath ./web):/web -w /web node:9.4-slim bash -c "npm install && npm start"
  web:
    image: "node:9.4-slim"
    links:
      - rabbitmq
    environment:
      - USER=${RASPBERRYPI_USER}
      - PASSWORD=${RASPBERRYPI_PASSWORD}
    volumes:
      - ./web:/web
    working_dir: /web
    ports:
      - 8080:8080
    command: npm run start-server
